---
language: python
sudo: required
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install tox-travis
  - pip install docker-py
  - pip install molecule
script:
  - tox
