---
- name: LDAP Authentication | Query ldap in nsswitch.conf
  replace:
    dest: /etc/nsswitch.conf
    regexp: '^({{ item }}(?!.*\bldap\b).*)$'
    replace: '\1 ldap'
    backup: yes
  with_items:
    - passwd
    - shadow
    - group