# Tasks file for ansible-role-ldap
---
# Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: LDAP Authentication | Query ldap in nsswitch.conf
  replace:
    dest: /etc/nsswitch.conf
    regexp: '^({{ item }}(?!.*\bldap\b).*)$'
    replace: '\1 ldap'
    backup: 'yes'
  with_items:
    - passwd
    - shadow
    - group

- name: "LDAP Authentication | Configure /etc/nslcd.conf"
  template:
    src: nslcd.conf.j2
    dest: /etc/nslcd.conf
    mode: 0600
  notify: restart services ldap
