---
- name: "LDAP Authentication | update package list"
  apt:
    update_cache: 'yes'
  changed_when: false

- name: "LDAP Authentication | Ensure ldap packages are present."
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ ldap_packages }}"

- name: "LDAP Authentication | Ensure services are running"
  service:
    name={{item}}
    enabled=yes
    state=started
  with_items:
    - "nscd"
    - "nslcd"
  register: services_ldap

- name: LDAP Authentication | Create Home Directories on login
  lineinfile:
    dest: /etc/pam.d/common-account
    regexp: 'pam_mkhomedir\.so'
    line: "session required pam_mkhomedir.so skel=/etc/skel/ umask={{ldap_home_umask}}"
    state: present
