---
- name: "LDAP Authentication | Ensure packages are present."
  yum:
    name: "{{ ldap_packages }}"
    state: present

- name: "LDAP Authentication | Ensure services are running"
  service:
    name={{item}}
    enabled=yes
    state=started
  with_items:
    - "nscd"
    - "nslcd"
    - "oddjobd"
  register: services_ldap

- name: "LDAP Authentication | Enable LDAP PAM modules"
  command: "authconfig --enableldap --enableldapauth --enablemkhomedir --update"
  changed_when: false
