# Molecule managed

FROM {{ item.image }}

ENV TERM=xterm

RUN if [ $(command -v apt-get) ]; then \
        apt-get update && apt-get upgrade -y && apt-get install -y \
            python \
            sudo \
            bash \
            git \
            coreutils \
            net-tools \
            ca-certificates \
            software-properties-common \
            python-software-properties \
        && apt-get clean && apt-get autoremove && apt-get clean && rm -rf /var/lib/apt/lists/*; \
# Install systemd -- See https://hub.docker.com/_/centos/
    elif [ $(command -v yum) ]; then \
        yum -y update && yum clean all \
        && (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done) \
        && rm -f /lib/systemd/system/multi-user.target.wants/* \
        && rm -f /etc/systemd/system/*.wants/* \
        && rm -f /lib/systemd/system/local-fs.target.wants/*  \
        && rm -f /lib/systemd/system/sockets.target.wants/*udev*  \
        && rm -f /lib/systemd/system/sockets.target.wants/*initctl*  \
        && rm -f /lib/systemd/system/basic.target.wants/* \
        && rm -f /lib/systemd/system/anaconda.target.wants/* \
        && yum update -y && yum install -y \
            python \
            wget \
            sudo \
            bash \
        && yum clean all \
        && sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers; fi